# Site settings
title: Blog about stuff
email: mkagenius@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome blog is here bro! Get ready to be mind = blow!
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://mkagenius.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mkagenius

# Build settings
markdown: kramdown
